services:
  redis:
    image: redis:7
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis-data:/data

  worldserver:
    build:
      context: .
      dockerfile: Dockerfile.world
    restart: always
    depends_on:
      - redis
    environment:
      - IS_DOCKER=true
      - ADMIN_DASHBOARD=true #8812938
    ports:
      - "2050:2050"
      - "2051:2051"
      - "2051:2051/udp"

  appserver:
    build:
      context: .
      dockerfile: Dockerfile.app
    restart: always
    depends_on:
      - redis
    environment:
      - IS_DOCKER=true
      - ADMIN_DASHBOARD=true #8812938
    ports:
      - "8888:8080"

  admindashboard: #8812938
    build:
      context: .
      dockerfile: Dockerfile.admin
    restart: always
    depends_on:
      - redis
      - worldserver
      - appserver
    environment:
      - IS_DOCKER=true
    ports:
      - "8889:8080"

volumes:
  redis-data:
